<li class="control medical" id="medical_history_div_new" style="display:block;">
              <?php //echo $this->getChildHtml('medicalhistory');?>
            <p class="f-left"><h4 class="medical_title">Medical Conditions </h4></p><!--a id="medical_history"  href="#medical_history_div">Add Medical History</a></p-->
            <div id="medical_history_div" class="detail" style="display:block;">
               <?php echo $this->getChildHtml('form.additional.info'); ?>
                <form name="longform" action="/index.php/medicalhistory/index" method="post" id="medicalobservationform">
                    <table border="0" cellpadding="0" cellspacing="0" width="70%">
                        <tbody>
                            <tr>
                                <td colspan="1" height="40"><strong>Primary Physician's Name : </strong></td>
                                <td><input type="text" class="physician_name"  style="width:250px;height:22px;" id="physician_name" name="Physician's Name"></td>
                            </tr>
                            <tr>
                                <td colspan="1" height="40"><strong>Physician's Telephone No : </strong> </td>
                                <td><input type="text" class="physician_telephone" style="width:250px;height:22px;" id="physician_telephone" name="Physician's Telephone"></td>
                               
                            </tr>

                            <tr>
                                <td colspan="2" height="30"><strong>Drug Allergies:</strong>
                                    <span>
                                        <input type="checkbox" class="medical_checkbox" id="drug_allergies" name="Drug Allergies"> None<br>
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2"><textarea name="Drug Allergies" class="medicaltextarea" cols="55" width="auto" id="drug_allergies_texarea" style="height:52px;"></textarea>
                                 <span id="drug_allergies_span" class="msgspan" style="background-color:#fff;color:#ff0000;font-weight:normal;display:none;">If you don't have any drug allergies, please check "None".</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                     <br>
                       <table border="0" cellpadding="0" cellspacing="0" width="70%">
                        <tbody>
                            <tr>
                                <td height="30"><strong>Current Medications:</strong>   
                                     <span>
                                       <input type="checkbox" class="medical_checkbox" id="current_medications" name="Current Medications" > None<br>
                                     </span>
                                </td>
                            </tr>
                            <tr>
                             
                                 <td colspan="2"><textarea name="Current Medications" class="medicaltextarea" cols="55" width="auto" id="current_medications_texarea" style="height:52px;"></textarea>
                                   <span id="current_medications_span" class="msgspan" style="background-color:#fff;color:#ff0000;font-weight:normal;display:none;">If you don't have any current medications, please check "None".</span>
                                 </td>
                            </tr>
                        </tbody>
                    </table>
                    <br/>
                      <table border="0" cellpadding="0" cellspacing="0" width="70%">
                        <tbody>
                            <tr>
                                <td height="30"><strong>Current Treatments:</strong>
                                     <span>
                                        <input type="checkbox" class="medical_checkbox" id="current_treatments" name="Current Treatments"> None<br>
                                     </span>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2"><textarea name="Current Treatments" class="medicaltextarea" cols="55" width="auto" id="current_treatments_texarea" style="height:52px;"></textarea>
                                  <span id="current_treatments_span" class="msgspan" style="background-color:#fff;color:#ff0000;font-weight:normal;display:none;">If you don't have any current treatments, please check "None".</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                     <br/>
                    <table border="0" cellpadding="0" cellspacing="0" width="70%">
                        <tbody>
                            <tr>
                                <td height="30"><strong> Other Conditions:</strong><br>
                                     <span>Do you smoke?
                                        <input type="radio" class="smoke_checkbox" value="no" checked="checked" name="Smoke">No 
                                        <input type="radio" class="smoke_checkbox" value="yes" name="Smoke">Yes<br>
                                     </span>
                                </td>
                            </tr>
                             <tr>
                                <td height="30">
                                     <span>Do you drink?
                                        <input type="radio" class="drink_radio" value="no"  checked="checked" name="Drink">No
                                        <input type="radio" class="drink_radio" value="yes" name="Drink">Yes<br>

                                     </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                     
                   <!--  <input name="SubmitMedical" class="btn_grn medicalhistory_btn" value="Add Medical History" onclick="submitmedicalhistory();" type="button"> -->
                                                
            </form>
        </div>
             
        </li>
         <div class="addedmedicalhistory" style="background-color:#fff;color:#819d01;font-weight:bold;display:none;">Medical History Added to your order</div>
    <?php //endif; ?>
    <li><p><b>
        I certify that I am 'over 18 years' and that I am under the supervision of a doctor. The ordered medication is for my own personal use and is strictly not meant for a re-sale. I also accept that I am taking the medicine /s at my own risk and that I am duly aware of all the effects / side effects of the medicine / s. I acknowledge that the drug is as per the norms of the country of destination.
    </b></p><br/>
    <p>By pressing 'continue' , I agree to the above statements.</p>
    </li>

    <script type="text/javascript">
 jQuery(document).ready(function() {
        jQuery('.medical_checkbox').click(function(){
          // alert(this.id);
            jQuery('#'+this.id+"_texarea").toggle();
            jQuery('#'+this.id+"_texarea").val('');
            jQuery('#'+this.id+"_span").css('display','none');

        });
        //code for the call and offers check
           jQuery('#callandoffers').change(function(){
          // alert(this.id);
          var callforoffersval = jQuery('#callandoffers').val();
          if(callforoffersval=='1'){
            jQuery('#callandoffers').val('0');
          }
           //alert(jQuery('#callandoffers').val());
            // jQuery('#'+this.id+"_texarea").toggle();
            // jQuery('#'+this.id+"_texarea").val('');
            // jQuery('#'+this.id+"_span").css('display','none');

        }); 

    });

//]]>
    function submitmedicalhistory(){
                //alert('hi');
        var url="<?php echo $this->getBaseUrl()?>"+'medicalhistory/index/storemedicalhistory';
        var drug_allergies = jQuery('#drug_allergies_texarea').val();
        var physician_name = jQuery('#physician_name').val();
        var physician_telephone = jQuery('#physician_telephone').val();
        var current_medications = jQuery('#current_medications_texarea').val();
        //alert(jQuery.type(current_medications));
        var current_treatments = jQuery('#current_treatments_texarea').val();
        //var smoke_treatments = jQuery('.smoke_checkbox').val();
        var smoke_treatments=jQuery('input:radio[name="Smoke"]:checked').val();
        var drink_treatments = jQuery('input:radio[name="Drink"]:checked').val();
        jQuery(".medical_checkbox").each(function(){
            if(jQuery("#"+this.id).is(':checked') == 1)
            {
                jQuery("#"+this.id+"_span").css('display','none');
            }
            else
            {
                 if(jQuery("#"+this.id).is(':checked') == 0){   
                   if(jQuery("#"+this.id+'_texarea').val()==''){
                        jQuery("#"+this.id+"_span").css('display','block');
                   }
                
                }

            }
        });
        // if(physician_telephone !='' && physicianname!='' && drug_allergies!='' && current_medications!='' && current_treatments!=''){
        //    <?php Mage::getSingleton('core/session')->unsInsertId();?>
        // }
       if(drug_allergies!='' || current_medications!='' || current_treatments!='' || physician_name!='' || physician_telephone!=''){

        var posting = jQuery.post( url, { physicianname: physician_name,physiciantelephone: physician_telephone,drugallergies: drug_allergies,currentmedications:current_medications,currenttreatments:current_treatments,smoke:smoke_treatments,drink:drink_treatments},function(result){
                if(result=='success'){
                    jQuery('#medical_history_div_new').hide(500, function(){
                    jQuery('.addedmedicalhistory').show();
                  });

               }
             });
       }


  //});
    }
    jQuery('.billingsavebtn').click(function(){

      // var timezonecode ="<?php echo $abbreviation['abbreviation']?>";
      var timezonecode =jQuery('#timezone').val();
      var timezoneval = jQuery('#timeval1').val()+'-'+jQuery('#timeval2').val()+' - ('+timezonecode+')'; 
      // alert(timezoneval);
      var all_clear = 0;
      var callandoffersurl="<?php echo $this->getBaseUrl()?>"+'callforoffer/index/callforoffersreg';
      var callforfree = jQuery('#callandoffers').val();
      var callforfreevar = jQuery.post( callandoffersurl, { callforfree: callforfree,timetocall:timezoneval},function(result){
               // return false;
             });


        var drug_allergies = jQuery('#drug_allergies_texarea').val();
        var current_medications = jQuery('#current_medications_texarea').val();
        var current_treatments = jQuery('#current_treatments_texarea').val();

        jQuery(".medical_checkbox").each(function(){
                if(jQuery("#"+this.id+"_texarea").val()=="" && jQuery("#"+this.id).is(':checked') == false) {
                    all_clear = 1;
                }                
        });
        //alert(all_clear);
        if(jQuery('#medical_history_div_new').css('display') == 'block') {
            submitmedicalhistory();
        }
        if(all_clear==0) {
            //alert("Hello");
            billing.save();
        }
    });
    jQuery('.billingsavebtn_').click(function(){
       // alert(jQuery('#callandoffers').val());
      // alert(jQuery('#callandoffers').val());
        var callandoffersurl="<?php echo $this->getBaseUrl()?>"+'callforoffer/index/callforoffersreg';
        var callforfree = jQuery('#callandoffers').val();
        var callforfreevar = jQuery.post( callandoffersurl, { callforfree: callforfree},function(result){
                //alert(result);
               // return false;
        });

        jQuery(".medicaltextarea").each(function(){
             if(jQuery("#"+this.id).val()=='')
                {
                  // alert('hi'); 
                   jQuery("#"+this.id).hide();
                   jQuery('.medical_checkbox').attr('checked',true);

                }
               
            });

    var drug_allergies = jQuery('#drug_allergies_texarea').val();
    var current_medications = jQuery('#current_medications_texarea').val();
    var current_treatments = jQuery('#current_treatments_texarea').val();

    if(drug_allergies!='' && current_medications!='' && current_treatments!=''){
    }
        if(jQuery('#medical_history_div_new').css('display') == 'block'){ submitmedicalhistory();}
    });

</script>
 
