<div class="account-create">
    <div class="page-title">
        <h1>Create an Account</h1>
    </div>
    <form action="http://localhost/m1/index.php/customer/account/createpost/" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="">
            <input type="hidden" name="error_url" value="">
            <h2 class="legend">Personal Information</h2>
            <ul class="form-list">
                 <li>
                    <label for="email_address" class="required"><em>*</em>Email Address</label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="" title="Email Address" class="input-text validate-email required-entry">
                    </div>
                </li>
               
                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                           <label for="companyname" class="required"><em>*</em>Company Name</label>
                           <div class="input-box">
                            <input type="text" name="companyname" id="companyname" value="" class="input-text required-entry">
                        </div>
                        </div>
                        <div class="field name-lastname">
                            <label for="website" class="required"><em>*</em>Website</label>
                            <div class="input-box">
                                <input type="text" id="website" name="website" value="" maxlength="255" class="input-text required-entry">
                            </div>
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="customer-name">
                        <div class="field name-firstname">
                            <label for="firstname" class="required"><em>*</em>First Name</label>
                            <div class="input-box">
                                <input type="text" id="firstname" name="firstname" value="" title="First Name" maxlength="255" class="input-text required-entry">
                            </div>
                        </div>
                        <div class="field name-lastname">
                            <label for="lastname" class="required"><em>*</em>Last Name</label>
                            <div class="input-box">
                                <input type="text" id="lastname" name="lastname" value="" title="Last Name" maxlength="255" class="input-text required-entry">
                            </div>
                        </div>
                    </div>
                </li>

                    <li class="fields">
                    <div class="phoneno">
                        <div class="field phoneno">
                            <label for="stdcode" class="required"><em>*</em>Std Code</label>
                            <div class="input-box">
                                <input type="text" id="stdcode" name="stdcode" value=""  maxlength="255" class="input-text validate-number required-entry">
                            </div>
                        </div>
                        <div class="field landlineno">
                            <label for="landlineno" class="required"><em>*</em>Landline No.</label>
                            <div class="input-box">
                                <input type="text" id="landlineno" name="landlineno" value="" maxlength="255" class="input-text validate-number required-entry">
                            </div>
                        </div>
                    </div>
                   </li>
                   <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em>Password</label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="Password" class="input-text required-entry validate-password">
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em>Confirm Password</label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="Confirm Password" id="confirmation" class="input-text required-entry validate-cpassword">
                        </div>
                    </div>
                </li>
                <li>
                    <label for="companyname" class="required">Attach your introduction letter/ Brochure</label>
                    <div class="input-box">
                        <input type="file" name="companyname" id="companyname" value="" class="input-text">
                </li>
               <!--  <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="Sign Up for Newsletter" value="1" id="is_subscribed" class="checkbox">
                    </div>
                    <label for="is_subscribed">Sign Up for Newsletter</label>
                </li> -->
            </ul>
        </div>
        <div class="fieldset">
            <h2 class="legend">Organisation structure</h2>
            <ul class="form-list">
              <li class="fields">
                <div class="phoneno">
                    <div class="field phoneno">
                        <label for="stdcode" class="required">Name</label>
                        <div class="input-box">
                            <input type="text" id="tree_name_1" name="tree_name[]" value=""  maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                    <div class="field landlineno">
                        <label for="landlineno" class="required">Reports to</label>
                        <div class="input-box">
                            <input type="text" id="landlineno" name="tree_name_reports_to[]" value="" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                    <div class="field landlineno">
                        <label for="landlineno" class="required">Department</label>
                        <div class="input-box">
                            <input type="text" id="landlineno" name="tree_org_dept[]" value="Sale" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                </div>
            </li>
              <li class="fields">
                <div class="phoneno">
                    <div class="field phoneno">
                        <label for="stdcode" class="required">Name</label>
                        <div class="input-box">
                            <input type="text" id="tree_name_1" name="tree_name[]" value=""  maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                    <div class="field landlineno">
                        <label for="landlineno" class="required">Reports to</label>
                        <div class="input-box">
                            <input type="text" id="landlineno" name="tree_name_reports_to[]" value="" maxlength="255" class="input-text required-entry">
                        </div>
                    </div>
                    <div class="field landlineno">
                        <label for="landlineno" class="required">Department</label>
                        <div class="input-box">
                            <select name="tree_org_dept[]">                               
                               <option value="Owner / Director">Owner / Director</option>
                               <option value="Accounts">Accounts</option>
                               <option value="Sale">Sale</option>
                               <option value="Purchase">Purchase</option>
                               <option value="Factory/ Site">Factory/ Site</option>
                               <option value="Stores">Stores</option>
                           </select>
                        </div>
                    </div>
                </div>
            </li>
            <li><span class="add_more_organization">Add More</span></li>
            <!-- <li><hr class="">Category/Business Type</hr><li> -->
        </ul></div>
        <div class="fieldset">
            <h2 class="legend">Category/Business Type</h2>
            <ul class="form-list">
            <li class="fields">
                <div class="phoneno">
                    <div class="field phoneno">
                        <input type="checkbox" id="authorized_dealer_chkbox" name="business_type[]" value="auth_dealer"  maxlength="255" class="">
                        <span> Authorized Dealer </span>                     
                    </div>
                    <div class="field landlineno">
                        <input type="checkbox" name="business_type[]" value="oem" maxlength="255" class="">
                        <span> Machine Manufacturer  </span>   
                    </div>
                    <div class="field landlineno">
                         <input type="checkbox" name="business_type[]" value="panel_builder" maxlength="255" class="">
                        <span> Panel Builder </span>   
                    </div>
                </div>
        </li>
              <li class="fields">
                <div class="phoneno">
                    <div class="field phoneno">
                        <input type="checkbox" name="business_type[]" value="e_u_i"  maxlength="255" class="">
                        <span> End User </span>                     

                </div>
                <div class="field landlineno">
                    <input type="checkbox" name="business_type[]" value="service_center" maxlength="255" class="">
                    <span>Service center </span>   
                </div>
                <div class="field landlineno">
                    <input type="checkbox" name="business_type[]" value="architect" maxlength="255" class="">
                    <span>  Retailer/ Supplier  </span>   
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="phoneno">
                <div class="field phoneno">
                    <input type="checkbox" name="business_type[]" value="retailer"  maxlength="255" class="">
                    <span>Architect </span>                     

                </div>
                <div class="field landlineno">
                    <input type="checkbox" name="business_type[]" value="elec_contractor" maxlength="255" class="">
                    <span> Electrical Contractor</span>   
                </div>
                <div class="field landlineno">
                    <input type="checkbox" name="business_type[]" value="consultant" maxlength="255" class="">
                    <span> Consultant </span>   
                </div>
            </div>
        </li>
        <li><h3>Authorized dealer for</h3></li>
        <li class="fields">
            <label for="email_address" class="required">Brand</label>
            <div class="input-box">
                <input type="text" name="auth_dealer_brand[]" id="email_address" value="" class="input-text">
            </div>
        </li>
           <li class="fields">
               <label for="email_address" class="required">Product category</label>
                    <div class="input-box">
                        <input type="text" name="auth_dealer_prod_cat[]" id="auth_dealer_prod_cat" value="" class="input-text">
                    </div>
        </li>  

        <li class="fields">
               <label for="email_address" class="required">Discount percent</label>
                    <div class="input-box">
                        <input type="text" name="auth_dealer_prod_cat_discount[]" id="" value="" class="input-text">
                    </div>
        </li>
           <li class="fields">
               <label for="email_address" class="required">Add dealership certificate</label>
                    <div class="input-box">
                        <input type="file" name="auth_dealer_cert[]" id="" value="" class="input-text">
                    </div>
        </li>
           <li class="fields">
               <label for="email_address" class="required">Company contact person name</label>
                    <div class="input-box">
                        <input type="text" name="auth_dealer_contact_person_name[]" id="" value="" class="input-text">
                    </div>
        </li>
  <li class="fields">
               <label for="email_address" class="required">Company contact person number</label>
                    <div class="input-box">
                        <input type="text" name="auth_dealer_contact_person_number[]" id="" value="" class="input-text">
                    </div>
        </li>

           <li class="fields">
               <label for="email_address" class="required">Add pricelist</label>
                    <div class="input-box">
                        <input type="file" name="auth_dealer_pricelist[]" id="" value="" class="input-text">
                    </div>
        </li>
           <li class="fields">
               <label for="email_address" class="required">Average stock in lacs</label>
                    <div class="input-box">
                        <input type="text" name="auth_dealer_stock" id="auth_dealer_stock[]" value="" class="input-text">
                    </div>
        </li>
         <li class="fields">
               <label for="email_address" class="required">Your inventory system(e.g. Tally/SAP )</label>
                    <div class="input-box">
                        <input type="text" name="inventory_system" id="inventory_system" value="" class="input-text">
                    </div>
        </li> 
           <li class="fields">
               <label for="email_address" class="required">Upload your stock</label>
                    <div class="input-box">
                        <input type="file" name="stock_info" id="stock_info" value="" class="input-text">
                    </div>
        </li>
        <li>Upload excel with your itemlist with columns as 1)Item code(SKU) 2)Description 3)Price 4) Maximum discount</li>
        <li class="fields">
           <label for="email_address" class="required"> ID :</label>
           <div class="input-box">
             <input type="text" name="salesperson" id="salesperson" class="input-text" value="">
         </div>
     </li>
     </ul></div>
        <div class="fieldset">
            <h2 class="legend">Company Description</h2>
            <ul class="form-list">
                   <li class="fields">
                    <div class="phoneno">
                        <div class="field yoe">
                            <label for="yoe" class="required">Year of Establishment</label>
                            <div class="input-box">
                                <input type="text" id="yoe" name="yoe" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field sister_companies">
                            <label for="sister_companies" class="required">Group companies/ Sister companies</label>
                            <div class="input-box">
                                <input type="text" id="sister_companies" name="sister_companies" value="" maxlength="255" class="input-text">
                            </div>
                        </div>
                    </div>
                   </li>
                      <li class="fields">
                    <div class="phoneno">
                        <div class="field no_of_employees">
                            <label for="no_of_employees" class="required">No. of Employees</label>
                            <div class="input-box">
                                <input type="text" id="no_of_employees" name="no_of_employees" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field pan_no">
                            <label for="pan_no" class="required">Pan No.</label>
                            <div class="input-box">
                                <input type="text" id="pan_no" name="pan_no" value="" maxlength="255" class="input-text">
                            </div>
                        </div>
                    </div>
                   </li>
                      <li class="fields">
                    <div class="phoneno">
                        <div class="field iec_code">
                            <label for="iec_code" class="required">IEC Code</label>
                            <div class="input-box">
                                <input type="text" id="iec_code" name="iec_code" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field psc">
                            <label for="psc" class="required">Proffessional,Standard Certifications</label>
                            <div class="input-box">
                                <input type="text" id="psc" name="psc" value="" maxlength="255" class="input-text">
                            </div>
                        </div>
                    </div>
                   </li>
            </ul></div>
        <div class="fieldset">
            <h2 class="legend">Address - Head Office</h2>
            <ul class="form-list">
                   <li class="fields">
                    <div class="phoneno">
                        <div class="field addr_line1">
                            <label for="addr_line1" class="required">Address</label>
                            <div class="input-box">
                                <input type="text" id="addr_line1" name="addr_line1" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field addr_line2">
                            <label for="addr_line2" class="required">Landmark</label>
                            <div class="input-box">
                                <input type="text" id="addr_line2" name="addr_line2" value="" maxlength="255" class="input-text">
                            </div>
                        </div>
                    </div>
                   </li>
                 
                      <li class="fields">
                    <div class="phoneno">
                        <div class="field phoneno">
                            <label for="stdcode" class="required">City</label>
                            <div class="input-box">
                                <!-- <input type="text" id="stdcode" name="stdcode" value=""  maxlength="255" class="input-text"> -->
                                <select name="city" id="city" >
                                    <option>    Default </option>
                                    <option>    Ananthnag   </option>
                                    <option>    Baramulla   </option>
                                    <option>    Budgam  </option>
                                    <option>    Doda    </option>
                                    <option>    Jammu   </option>
                                    <option>    Kargil  </option>
                                    <option>    Kathua  </option>
                                    <option>    Kupwara </option>
                                    <option>    Leh </option>
                                    <option>    Poonch  </option>
                                    <option>    Pulwama </option>
                                    <option>    Rajauri </option>
                                    <option>    Srinagar    </option>
                                    <option>    Udhampur    </option>
                                    <option>    Bilaspur    </option>
                                    <option>    Chamba  </option>
                                    <option>    Hamirpur    </option>
                                    <option>    Kangra  </option>
                                    <option>    Kinnaur </option>
                                    <option>    Kullu   </option>
                                    <option>    Lahul & spiti   </option>

                                    <option>    Mumbai  </option>
                                    <option>    Mandi   </option>
                                    <option>    Shimla  </option>
                                    <option>    Sirmaur </option>
                                    <option>    Solan   </option>
                                    <option>    Una </option>
                                    <option>    Chandigarh  </option>
                                    <option>    Amritsar    </option>
                                    <option>    Bathinda    </option>
                                    <option>    Faridkot    </option>
                                    <option>    Fatehgarh Sahib </option>
                                    <option>    Firozpur    </option>
                                    <option>    Gurdaspur   </option>
                                    <option>    Hoshiarpur  </option>
                                    <option>    Jalandhar   </option>
                                    <option>    Kapurthala  </option>
                                    <option>    Ludhiana    </option>
                                    <option>    Mansa   </option>
                                    <option>    Moga    </option>
                                    <option>    Mohali  </option>
                                    <option>    Muktsar </option>
                                    <option>    Nawanshahr  </option>
                                    <option>    Patiala </option>
                                    <option>    Ropar (rupnagar)    </option>
                                    <option>    Sangrur </option>
                                    <option>    Ambala  </option>
                                    <option>    Bhiwani </option>
                                    <option>    Faridabad   </option>
                                    <option>    Fatehabad   </option>
                                    <option>    Gurgaon </option>
                                    <option>    Hisar   </option>
                                    <option>    Jhajjar </option>
                                    <option>    Jind    </option>
                                    <option>    Kaithal </option>
                                    <option>    Karnal  </option>
                                    <option>    Kurukshetra </option>
                                    <option>    Mahendragarh    </option>
                                    <option>    Panchkula   </option>
                                    <option>    Panipat </option>
                                    <option>    Rewari  </option>
                                    <option>    Rohtak  </option>
                                    <option>    Sirsa   </option>
                                    <option>    Sonipat </option>
                                    <option>    Yamuna Nagar    </option>
                                    <option>    Central Delhi   </option>
                                    <option>    East Delhi  </option>
                                    <option>    New Delhi   </option>
                                    <option>    North Delhi </option>
                                    <option>    North West delhi    </option>
                                    <option>    South Delhi </option>
                                    <option>    South West delhi    </option>
                                    <option>    West Delhi  </option>
                                    <option>    Almora  </option>
                                    <option>    Bageshwar   </option>
                                    <option>    Chamoli </option>
                                    <option>    Champawat   </option>
                                    <option>    Dehradun    </option>
                                    <option>    Haridwar    </option>
                                    <option>    Nainital    </option>
                                    <option>    Pauri Garhwal   </option>
                                    <option>    Pithoragarh </option>
                                    <option>    Rudraprayag </option>
                                    <option>    Tehri Garhwal   </option>
                                    <option>    Udham Singh nagar   </option>
                                    <option>    Uttarkashi  </option>
                                    <option>    Agra    </option>
                                    <option>    Aligarh </option>
                                    <option>    Allahabad   </option>
                                    <option>    Ambedkar Nagar  </option>
                                    <option>    Auraiya </option>
                                    <option>    Azamgarh    </option>
                                    <option>    Bagpat  </option>
                                    <option>    Bahraich    </option>
                                    <option>    Ballia  </option>
                                    <option>    Balrampur   </option>
                                    <option>    Banda   </option>
                                    <option>    Barabanki   </option>
                                    <option>    Bareilly    </option>
                                    <option>    Basti   </option>
                                    <option>    Bijnor  </option>
                                    <option>    Budaun  </option>
                                    <option>    Bulandshahr </option>
                                    <option>    Chandauli   </option>
                                    <option>    Chitrakoot  </option>
                                    <option>    Deoria  </option>
                                    <option>    Etah    </option>
                                    <option>    Etawah  </option>
                                    <option>    Faizabad    </option>
                                    <option>    Farrukhabad </option>
                                    <option>    Fatehpur    </option>
                                    <option>    Firozabad   </option>
                                    <option>    Gautam Buddha nagar </option>
                                    <option>    Ghaziabad   </option>
                                    <option>    Ghazipur    </option>
                                    <option>    Gonda   </option>
                                    <option>    Gorakhpur   </option>
                                    <option>    Hardoi  </option>
                                    <option>    Hathras </option>
                                    <option>    Jalaun  </option>
                                    <option>    Jaunpur </option>
                                    <option>    Jhansi  </option>
                                    <option>    Jyotiba Phule nagar </option>
                                    <option>    Kannauj </option>
                                    <option>    Kanpur Dehat    </option>
                                    <option>    Kanpur Nagar    </option>
                                    <option>    Kaushambi   </option>
                                    <option>    Kheri   </option>
                                    <option>    Kushinagar  </option>
                                    <option>    Lalitpur    </option>
                                    <option>    Lucknow </option>
                                    <option>    Maharajganj </option>
                                    <option>    Mahoba  </option>
                                    <option>    Mainpuri    </option>
                                    <option>    Mathura </option>
                                    <option>    Mau </option>
                                    <option>    Meerut  </option>
                                    <option>    Mirzapur    </option>
                                    <option>    Moradabad   </option>
                                    <option>    Muzaffarnagar   </option>
                                    <option>    Pilibhit    </option>
                                    <option>    Pratapgarh  </option>
                                    <option>    Raebareli   </option>
                                    <option>    Rampur  </option>
                                    <option>    Saharanpur  </option>
                                    <option>    Sant Kabir nagar    </option>
                                    <option>    Sant Ravidas nagar  </option>
                                    <option>    Shahjahanpur    </option>
                                    <option>    Shrawasti   </option>
                                    <option>    Siddharthnagar  </option>
                                    <option>    Sitapur </option>
                                    <option>    Sonbhadra   </option>
                                    <option>    Sultanpur   </option>
                                    <option>    Unnao   </option>
                                    <option>    Varanasi    </option>
                                    <option>    Araria  </option>
                                    <option>    Aurangabad  </option>
                                    <option>    Banka   </option>
                                    <option>    Begusarai   </option>
                                    <option>    Bhagalpur   </option>
                                    <option>    Bhojpur </option>
                                    <option>    Buxar   </option>
                                    <option>    Darbhanga   </option>
                                    <option>    East Champaran  </option>
                                    <option>    Gaya    </option>
                                    <option>    Gopalganj   </option>
                                    <option>    Jamui   </option>
                                    <option>    Jehanabad   </option>
                                    <option>    Kaimur (bhabua) </option>
                                    <option>    Katihar </option>
                                    <option>    Khagaria    </option>
                                    <option>    Kishanganj  </option>
                                    <option>    Lakhisarai  </option>
                                    <option>    Madhepura   </option>
                                    <option>    Madhubani   </option>
                                    <option>    Munger  </option>
                                    <option>    Muzaffarpur </option>
                                    <option>    Nalanda </option>
                                    <option>    Nawada  </option>
                                    <option>    Patna   </option>
                                    <option>    Purnia  </option>
                                    <option>    Rohtas  </option>
                                    <option>    Saharsa </option>
                                    <option>    Samastipur  </option>
                                    <option>    Saran   </option>
                                    <option>    Sheikhpura  </option>
                                    <option>    Sheohar </option>
                                    <option>    Sitamarhi   </option>
                                    <option>    Siwan   </option>
                                    <option>    Supaul  </option>
                                    <option>    Vaishali    </option>
                                    <option>    West Champaran  </option>
                                    <option>    Bankura </option>
                                    <option>    Bardhaman   </option>
                                    <option>    Birbhum </option>
                                    <option>    Cooch Behar </option>
                                    <option>    Darjeeling  </option>
                                    <option>    East Medinipur  </option>
                                    <option>    Hooghly </option>
                                    <option>    Howrah  </option>
                                    <option>    Jalpaiguri  </option>
                                    <option>    Kolkata </option>
                                    <option>    Malda   </option>
                                    <option>    Murshidabad </option>
                                    <option>    Nadia   </option>
                                    <option>    North 24 parganas   </option>
                                    <option>    North Dinajpur (uttar)  </option>
                                    <option>    Purulia </option>
                                    <option>    South 24 parganas   </option>
                                    <option>    South Dinajpur (dakshin)    </option>
                                    <option>    West Medinipur  </option>
                                    <option>    West Midnapore  </option>
                                    <option>    Bokaro  </option>
                                    <option>    Chatra  </option>
                                    <option>    Deoghar </option>
                                    <option>    Dhanbad </option>
                                    <option>    Dumka   </option>
                                    <option>    East Singhbhum  </option>
                                    <option>    Garhwa  </option>
                                    <option>    Giridh  </option>
                                    <option>    Godda   </option>
                                    <option>    Gumla   </option>
                                    <option>    Hazaribag   </option>
                                    <option>    Jamtara </option>
                                    <option>    Koderma </option>
                                    <option>    Latehar </option>
                                    <option>    Lohardaga   </option>
                                    <option>    Pakur   </option>
                                    <option>    Palamau </option>
                                    <option>    Ramgarh </option>
                                    <option>    Ranchi  </option>
                                    <option>    Sahibganj   </option>
                                    <option>    Simdega </option>
                                    <option>    West Singhbhum  </option>
                                    <option>    Seraikela-kharsawan </option>
                                    <option>    Angul   </option>
                                    <option>    Balangir    </option>
                                    <option>    Baleswar    </option>
                                    <option>    Bargarh </option>
                                    <option>    Bhadrak </option>
                                    <option>    Boudh   </option>
                                    <option>    Cuttack </option>
                                    <option>    Debagarh (deogarh)  </option>
                                    <option>    Dhenkanal   </option>
                                    <option>    Gajapati    </option>
                                    <option>    Ganjam  </option>
                                    <option>    Jagatsinghapur  </option>
                                    <option>    Jajapur </option>
                                    <option>    Jharsuguda  </option>
                                    <option>    Kalahandi   </option>
                                    <option>    Kandhamal   </option>
                                    <option>    Kendrapara  </option>
                                    <option>    Kendujhar   </option>
                                    <option>    Khurda (khordha)    </option>
                                    <option>    Koraput </option>
                                    <option>    Malkangiri  </option>
                                    <option>    Mayurbhanj  </option>
                                    <option>    Nabarangapur    </option>
                                    <option>    Nayagarh    </option>
                                    <option>    Nuapada </option>
                                    <option>    Puri    </option>
                                    <option>    Rayagada    </option>
                                    <option>    Sambalpur   </option>
                                    <option>    Sonapur (subarnapur)    </option>
                                    <option>    Sundergarh  </option>
                                    <option>    Bastar  </option>
                                    <option>    Bijapur </option>
                                    <option>    Dantewada   </option>
                                    <option>    Dhamtari    </option>
                                    <option>    Durg    </option>
                                    <option>    Janjgir-champa  </option>
                                    <option>    Jashpur </option>
                                    <option>    Kanker  </option>
                                    <option>    Kawardha    </option>
                                    <option>    Korba   </option>
                                    <option>    Koriya  </option>
                                    <option>    Mahasamund  </option>
                                    <option>    Narayanpur  </option>
                                    <option>    Raigarh </option>
                                    <option>    Raipur  </option>
                                    <option>    Rajnandgaon </option>
                                    <option>    Surguja </option>
                                    <option>    Anuppur </option>
                                    <option>    Ashoknagar  </option>
                                    <option>    Balaghat    </option>
                                    <option>    Barwani </option>
                                    <option>    Betul   </option>
                                    <option>    Bhind   </option>
                                    <option>    Bhopal  </option>
                                    <option>    Burhanpur   </option>
                                    <option>    Chhatarpur  </option>
                                    <option>    Chhindwara  </option>
                                    <option>    Damoh   </option>
                                    <option>    Datia   </option>
                                    <option>    Dewas   </option>
                                    <option>    Dhar    </option>
                                    <option>    Dindori </option>
                                    <option>    Guna    </option>
                                    <option>    Gwalior </option>
                                    <option>    Harda   </option>
                                    <option>    Hoshangabad </option>
                                    <option>    Indore  </option>
                                    <option>    Jabalpur    </option>
                                    <option>    Jhabua  </option>
                                    <option>    Katni   </option>
                                    <option>    Khandwa (east nimar)    </option>
                                    <option>    Khargone (west nimar)   </option>
                                    <option>    Mandla  </option>
                                    <option>    Mandsaur    </option>
                                    <option>    Morena  </option>
                                    <option>    Narsinghpur </option>
                                    <option>    Neemuch </option>
                                    <option>    Panna   </option>
                                    <option>    Raisen  </option>
                                    <option>    Ratlam  </option>
                                    <option>    Rewa    </option>
                                    <option>    Satna   </option>
                                    <option>    Seoni   </option>
                                    <option>    Shahdol </option>
                                    <option>    Shajapur    </option>
                                    <option>    Sheopur </option>
                                    <option>    Shivpuri    </option>
                                    <option>    Sidhi   </option>
                                    <option>    Tikamgarh   </option>
                                    <option>    Ujjain  </option>
                                    <option>    Umaria  </option>
                                    <option>    Vidisha </option>
                                    <option>    Ajmer   </option>
                                    <option>    Alwar   </option>
                                    <option>    Banswara    </option>
                                    <option>    Baran   </option>
                                    <option>    Barmer  </option>
                                    <option>    Bharatpur   </option>
                                    <option>    Bhilwara    </option>
                                    <option>    Bikaner </option>
                                    <option>    Bundi   </option>
                                    <option>    Chittorgarh </option>
                                    <option>    Churu   </option>
                                    <option>    Dausa   </option>
                                    <option>    Dholpur </option>
                                    <option>    Dungarpur   </option>
                                    <option>    Hanumangarh </option>
                                    <option>    Jaipur  </option>
                                    <option>    Jaisalmer   </option>
                                    <option>    Jalor   </option>
                                    <option>    Jhalawar    </option>
                                    <option>    Jhunjhunu   </option>
                                    <option>    Jodhpur </option>
                                    <option>    Karauli </option>
                                    <option>    Kota    </option>
                                    <option>    Nagaur  </option>
                                    <option>    Pali    </option>
                                    <option>    Rajsamand   </option>
                                    <option>    Sawai Madhopur  </option>
                                    <option>    Sikar   </option>
                                    <option>    Sirohi  </option>
                                    <option>    Sri Ganganagar  </option>
                                    <option>    Tonk    </option>
                                    <option>    Udaipur </option>
                                    <option>    Ahmedabad   </option>
                                    <option>    Amreli  </option>
                                    <option>    Anand   </option>
                                    <option>    Banaskantha </option>
                                    <option>    Bharuch </option>
                                    <option>    Bhavnagar   </option>
                                    <option>    Dahod   </option>
                                    <option>    Gandhi Nagar    </option>
                                    <option>    Jamnagar    </option>
                                    <option>    Junagadh    </option>
                                    <option>    Kachchh </option>
                                    <option>    Kheda   </option>
                                    <option>    Mahesana    </option>
                                    <option>    Narmada </option>
                                    <option>    Navsari </option>
                                    <option>    Panch Mahals    </option>
                                    <option>    Patan   </option>
                                    <option>    Porbandar   </option>
                                    <option>    Rajkot  </option>
                                    <option>    Sabarkantha </option>
                                    <option>    Surat   </option>
                                    <option>    Surendra Nagar  </option>
                                    <option>    The Dangs   </option>
                                    <option>    Vadodara    </option>
                                    <option>    Valsad  </option>
                                    <option>    Daman   </option>
                                    <option>    Diu </option>
                                    <option>    Dadra & nagar haveli    </option>
                                    <option>    Thane   </option>
                                    <option>    North Goa   </option>
                                    <option>    South Goa   </option>
                                    <option>    Adilabad    </option>
                                    <option>    Anantapur   </option>
                                    <option>    Chittoor    </option>
                                    <option>    Cuddapah    </option>
                                    <option>    East Godavari   </option>
                                    <option>    Guntur  </option>
                                    <option>    Hyderabad   </option>
                                    <option>    Karim Nagar </option>
                                    <option>    Khammam </option>
                                    <option>    Krishna </option>
                                    <option>    Kurnool </option>
                                    <option>    Mahabubnagar    </option>
                                    <option>    Medak   </option>
                                    <option>    Nalgonda    </option>
                                    <option>    Nellore </option>
                                    <option>    Nizamabad   </option>
                                    <option>    Prakasam    </option>
                                    <option>    Rangareddi  </option>
                                    <option>    Srikakulam  </option>
                                    <option>    Visakhapatnam   </option>
                                    <option>    Vizianagaram    </option>
                                    <option>    Warangal    </option>
                                    <option>    West Godavari   </option>
                                    <option>    Bagalkot    </option>
                                    <option>    Bangalore   </option>
                                    <option>    Bangalore Rural </option>
                                    <option>    Belgaum </option>
                                    <option>    Bellary </option>
                                    <option>    Bidar   </option>
                                    <option>    Chamrajnagar    </option>
                                    <option>    Chickmagalur    </option>
                                    <option>    Chitradurga </option>
                                    <option>    Dakshina Kannada    </option>
                                    <option>    Davangare   </option>
                                    <option>    Dharward    </option>
                                    <option>    Gadag   </option>
                                    <option>    Gulbarga    </option>
                                    <option>    Hassan  </option>
                                    <option>    Haveri  </option>
                                    <option>    Kodagu  </option>
                                    <option>    Kolar   </option>
                                    <option>    Koppal  </option>
                                    <option>    Mandya  </option>
                                    <option>    Mysore  </option>
                                    <option>    Raichur </option>
                                    <option>    Shimoga </option>
                                    <option>    Tumkur  </option>
                                    <option>    Udupi   </option>
                                    <option>    Uttara Kannada  </option>
                                    <option>    Alappuzha   </option>
                                    <option>    Ernakulam   </option>
                                    <option>    Idukki  </option>
                                    <option>    Kannur  </option>
                                    <option>    Kasargod    </option>
                                    <option>    Kollam  </option>
                                    <option>    Kottayam    </option>
                                    <option>    Kozhikode   </option>
                                    <option>    Malappuram  </option>
                                    <option>    Palakkad    </option>
                                    <option>    Pathanamthitta  </option>
                                    <option>    Thiruvananthapuram  </option>
                                    <option>    Thrissur    </option>
                                    <option>    Wayanad </option>
                                    <option>    Ariyalur    </option>
                                    <option>    Chennai </option>
                                    <option>    Coimbatore  </option>
                                    <option>    Cuddalore   </option>
                                    <option>    Dharmapuri  </option>
                                    <option>    Dindigul    </option>
                                    <option>    Erode   </option>
                                    <option>    Kanchipuram </option>
                                    <option>    Kanyakumari </option>
                                    <option>    Karur   </option>
                                    <option>    Krishnagiri </option>
                                    <option>    Madurai </option>
                                    <option>    Nagapattinam    </option>
                                    <option>    Namakkal    </option>
                                    <option>    Nilgiris    </option>
                                    <option>    Perambalur  </option>
                                    <option>    Pudukkottai </option>
                                    <option>    Ramanathapuram  </option>
                                    <option>    Salem   </option>
                                    <option>    Sivaganga   </option>
                                    <option>    Thanjavur   </option>
                                    <option>    Theni   </option>
                                    <option>    Tiruchirappalli </option>
                                    <option>    Tirunelveli </option>
                                    <option>    Tiruvallur  </option>
                                    <option>    Tiruvannamalai  </option>
                                    <option>    Tiruvarur   </option>
                                    <option>    Tuticorin ( thoothukudi )   </option>
                                    <option>    Vellore </option>
                                    <option>    Villupuram  </option>
                                    <option>    Virudhunagar    </option>
                                    <option>    North And middle andaman    </option>
                                    <option>    South Andaman   </option>
                                    <option>    Nicobar </option>
                                    <option>    Karaikal    </option>
                                    <option>    Mahe    </option>
                                    <option>    Pondicherry </option>
                                    <option>    Lakshadweep </option>
                                    <option>    East Sikkim </option>
                                    <option>    North Sikkim    </option>
                                    <option>    South Sikkim    </option>
                                    <option>    West Sikkim </option>
                                    <option>    Barpeta </option>
                                    <option>    Bongaigaon  </option>
                                    <option>    Cachar  </option>
                                    <option>    Darrang </option>
                                    <option>    Dhemaji </option>
                                    <option>    Dhubri  </option>
                                    <option>    Dibrugarh   </option>
                                    <option>    Goalpara    </option>
                                    <option>    Golaghat    </option>
                                    <option>    Hailakandi  </option>
                                    <option>    Jorhat  </option>
                                    <option>    Kamrup  </option>
                                    <option>    Karbi Anglong   </option>
                                    <option>    Karimganj   </option>
                                    <option>    Kokrajhar   </option>
                                    <option>    Lakhimpur   </option>
                                    <option>    Marigaon    </option>
                                    <option>    Nagaon  </option>
                                    <option>    Nalbari </option>
                                    <option>    North Cachar hills  </option>
                                    <option>    Sivasagar (sibsagar)    </option>
                                    <option>    Sonitpur    </option>
                                    <option>    Tinsukia    </option>
                                    <option>    Changlang   </option>
                                    <option>    Dibang Valley   </option>
                                    <option>    East Kameng </option>
                                    <option>    East Siang  </option>
                                    <option>    Kurung Kumey    </option>
                                    <option>    Lohit   </option>
                                    <option>    Lower Dibang valley </option>
                                    <option>    Lower Subansiri </option>
                                    <option>    Papum Pare  </option>
                                    <option>    Tawang  </option>
                                    <option>    Tirap   </option>
                                    <option>    Upper Siang </option>
                                    <option>    Upper Subansiri </option>
                                    <option>    West Kameng </option>
                                    <option>    West Siang  </option>
                                    <option>    East Garo hills </option>
                                    <option>    East Khasi hills    </option>
                                    <option>    Jaintia Hills   </option>
                                    <option>    Ri Bhoi </option>
                                    <option>    South Garo hills    </option>
                                    <option>    West Garo hills </option>
                                    <option>    West Khasi hills    </option>
                                    <option>    Dhalai  </option>
                                    <option>    North Tripura   </option>
                                    <option>    South Tripura   </option>
                                    <option>    West Tripura    </option>
                                    <option>    Aizawl  </option>
                                    <option>    Champhai    </option>
                                    <option>    Kolasib </option>
                                    <option>    Lawngtlai   </option>
                                    <option>    Lunglei </option>
                                    <option>    Mammit  </option>
                                    <option>    Saiha   </option>
                                    <option>    Serchhip    </option>
                                    <option>    Bishnupur   </option>
                                    <option>    Chandel </option>
                                    <option>    Churachandpur   </option>
                                    <option>    Imphal East </option>
                                    <option>    Imphal West </option>
                                    <option>    Senapati    </option>
                                    <option>    Tamenglong  </option>
                                    <option>    Thoubal </option>
                                    <option>    Ukhrul  </option>
                                    <option>    Dimapur </option>
                                    <option>    Kiphire </option>
                                    <option>    Kohima  </option>
                                    <option>    Longleng    </option>
                                    <option>    Mokokchung  </option>
                                    <option>    Mon </option>
                                    <option>    Peren   </option>
                                    <option>    Phek    </option>
                                    <option>    Tuensang    </option>
                                    <option>    Wokha   </option>
                                    <option>    Zunhebotto  </option>
                                </select>
                            </div>
                        </div>
                        <div class="field landlineno">
                            <label for="landlineno" class="required">State</label>
                            <div class="input-box">
                                <!-- <input type="text" id="landlineno" name="landlineno" value="" maxlength="255" class="input-text validate-number"> -->
                                <select id="addr_ho_state" name="state">
                                    <option>Default </option>       
                                    <option>    Jammu &amp; kashmir </option>
                                    <option>    Himachal Pradesh    </option>
                                    <option>    Chandigarh  </option>
                                    <option>    Punjab  </option>
                                    <option>    Haryana </option>
                                    <option>    Delhi   </option>
                                    <option>    Uttarakhand </option>
                                    <option>    Uttar Pradesh   </option>
                                    <option>    Bihar   </option>
                                    <option>    West Bengal </option>
                                    <option>    Jharkhand   </option>
                                    <option>    Orissa  </option>
                                    <option>    Chhattisgarh    </option>
                                    <option>    Madhya Pradesh  </option>
                                    <option>    Rajasthan   </option>
                                    <option>    Gujarat </option>
                                    <option>    Daman & diu </option>
                                    <option>    Dadra & nagar haveli    </option>
                                    <option>    Maharashtra </option>
                                    <option>    Goa </option>
                                    <option>    Andhra Pradesh  </option>
                                    <option>    Karnataka   </option>
                                    <option>    Kerala  </option>
                                    <option>    Tamil Nadu  </option>
                                    <option>    Andaman & nicobar islands   </option>
                                    <option>    Pondicherry </option>
                                    <option>    Lakshadweep </option>
                                    <option>    Sikkim  </option>
                                    <option>    Assam   </option>
                                    <option>    Arunachal Pradesh   </option>
                                    <option>    Meghalaya   </option>
                                    <option>    Tripura </option>
                                    <option>    Mizoram </option>
                                    <option>    Manipur </option>
                                    <option>    Nagaland    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                   </li>
                        <li class="fields">
                    <div class="phoneno">
                        <div class="field pincode">
                            <label for="pincode" class="required">Pincode No.</label>
                            <div class="input-box">
                                <input type="text" id="pincode" name="pincode" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field location">
                            <label for="location" class="required">Location</label>
                            <div class="input-box">
                                <input type="text" id="location" name="location" value="" maxlength="255" class="input-text validate-number">
                            </div>
                        </div>
                    </div>
                   </li>
            </ul>
            </div>
        <div class="fieldset">
            <h2 class="legend">Top Projects Executed</h2>
            <h2 class="">Testmonials / References</h2>
            <ul class="form-list">
                   <li class="fields">
                    <div class="phoneno">
                        <div class="field company_name">
                            <label for="company_name" class="required">Project name</label>
                            <div class="input-box">
                                <input type="text" id="company_name" name="project_company_name[]" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field project_location">
                            <label for="project_location" class="required">Location</label>
                            <div class="input-box">
                                <input type="text" id="location" name="project_location" value="" maxlength="255" class="input-text validate-number">
                            </div>
                        </div>
                    </div>
                   </li>
                          <li class="fields">
                    <div class="phoneno">
                        <div class="field pincode">
                            <label for="pincode" class="required">Industry</label>
                            <div class="input-box">
                                <!-- <input type="text" id="pincode" name="pincode" value=""  maxlength="255" class="input-text"> -->
                                <select name="project_industry[]">
                                  <option>  Automotive  </option>
                                  <option>  Chemical    </option>
                                  <option>  Utility</option>
                                  <option>  Pharmaceuticals     </option>
                                  <option>  Real Estate     </option>
                                  <option>  Cement</option>
                                  <option>  Steel</option>
                                  <option>  Textile</option>
                                  <option>  Technology  </option>
                                  <option>  Other</option>
                              </select>
                            </div>
                        </div>
                        <div class="field location">
                            <label for="location" class="required">Name</label>
                            <div class="input-box">
                                <input type="text" id="location" name="location" value="" maxlength="255" class="input-text validate-number">
                            </div>
                        </div>
                    </div>
                   </li>
                          <li class="fields">
                    <div class="phoneno">
                        <div class="field phone_no_verify">
                            <label for="phone_no_verify" class="required">Phone No. for verification</label>
                            <div class="input-box">
                                <input type="text" id="phone_no_verify" name="project_phone_no_verify[]" value=""  maxlength="255" class="input-text">
                            </div>
                        </div>
                        <div class="field location">
                            <label for="location" class="required">Value in Lacs</label>
                            <div class="input-box">
                                <input type="text" id="value_in_lacs" name="project_value_in_lacs" value="" maxlength="255" class="input-text validate-number">
                            </div>
                        </div>
                    </div>
                   </li>
            <ul class="form-list">
            </ul>
        </div>
        <div class="fieldset">
            <h2 class="legend">Major Customers</h2>
            <ul class="form-list">
             <li class="fields">
                <div class="phoneno">
                    <div class="field company_name">
                        <label for="company_name" class="required">Customer Name</label>
                        <div class="input-box">
                            <input type="text" name="major_customer_name[]" value=""  maxlength="255" class="input-text">
                        </div>
                    </div>
                    <div class="field project_location">
                        <label for="project_location" class="required">Customer Name</label>
                        <div class="input-box">
                            <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text">
                        </div>
                    </div>
                </div>
            </li>
            <li>ADD MORE Customer</li>
                <li class="fields">
                <div class="phoneno">
                    <div class="field company_name">
                        <label for="company_name" class="required">Add Testimonials</label>
                        <div class="input-box">
                            <input type="file" name="testimonials" value=""  maxlength="255" class="input-text">
                            (Add files of the testimonials received)
                        </div>
                    </div>
                 
                </div>
            </li>
        </ul>
    </div>
         <div class="fieldset">
            <h2 class="legend">Credentials</h2>
            <ul class="form-list">
              <li class="fields">
                <!-- <div class="phoneno"> -->
                    <!-- <div class="field company_name"> -->
                        <label for="company_name" class="required">Total Annual Sales Volume in Lacs Yr Ended March 2013</label>
                        <div class="input-box">
                            <input type="text" name="major_customer_name[]" value=""  maxlength="255" class="input-text">
                        <!-- </div> -->
                    <!-- </div> -->
         
                </div>
            </li>
                          <li class="fields">
                <!-- <div class="phoneno"> -->
               
                    <!-- <div class="field project_location"> -->
                        <label for="project_location" class="required">Expected Annual Sales Volume in Lacs Yr Ended March 2014</label>
                        <div class="input-box">
                            <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text">
                        <!-- </div> -->
                    <!-- </div> -->
                </div>
            </li>
            </ul>
        </div>
         <div class="fieldset">
            <h2 class="legend">Your detailed company page</h2>
            <ul class="form-list">
              <li class="fields">
                <label for="project_location" class="required">Main Products / Services Offered</label>
                <div class="input-box">
                     <textarea name="main_products"></textarea>
                </div>
            </li>
            <li class="fields">
                <label for="project_location" class="required">Photos of your products/ installations/ projects executed</label>
                <div class="input-box">
                    <!-- <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text"> -->
                    <input name="product_photos" type="file" id="" class="input-text" />
                   
                </div>
            </li>
            <li class="fields">
                <label for="project_location" class="required">Highlight USP/Special Benefits of your Product/Services over Competition</label>
                <div class="input-box">
                    <!-- <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text"> -->
                    <textarea class="span9" name="usp"></textarea>
                </div>
            </li>
            <li class="fields">
                <label for="project_location" class="required">Company Video URL</label>
                <div class="input-box">
                    <!-- <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text"> -->
                    <input type="text" name="video" id="comp_vid_url" class="input-text"/>
                </div>
            </li>
            <li class="fields">
                <label for="project_location" class="required">Company Photos</label>
                <div class="input-box">
                    <!-- <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text"> -->
                    <input type="file" name="company_photos" class="input-text" />
                </div>
            </li> 
            <li class="fields">
                <label for="project_location" class="required">Our Associate Concerns</label>
                <div class="input-box">
                    <!-- <input type="text" name="major_customer_name[]" value="" maxlength="255" class="input-text"> -->
                    <textarea class="span9" name="associate"></textarea>
                </div>
            </li>

            </ul>
        </div>
            <script type="text/javascript">

            </script>

            <script type="text/javascript">
//<![CDATA[
function toggleRememberMepopup(event){
    if($('remember-me-popup')){
        var viewportHeight = document.viewport.getHeight(),
        docHeight      = $$('body')[0].getHeight(),
        height         = docHeight > viewportHeight ? docHeight : viewportHeight;
        $('remember-me-popup').toggle();
        $('window-overlay').setStyle({ height: height + 'px' }).toggle();
    }
    Event.stop(event);
}

document.observe("dom:loaded", function() {
    new Insertion.Bottom($$('body')[0], $('window-overlay'));
    new Insertion.Bottom($$('body')[0], $('remember-me-popup'));

    $$('.remember-me-popup-close').each(function(element){
        Event.observe(element, 'click', toggleRememberMepopup);
    })
    $$('#remember-me-box a').each(function(element) {
        Event.observe(element, 'click', toggleRememberMepopup);
    });
});
//]]>
</script>
</div>
<div class="buttons-set">
    <p class="required">* Required Fields</p>
    <p class="back-link"><a href="http://localhost/m1/index.php/customer/account/login/" class="back-link"><small>« </small>Back</a></p>
    <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
</div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
            //]]>
            </script>
        </div>