<div class="below_banner_main_area">
	<div class="below_banner_area">
		<div class="how_to_order">
			<img src="<?php echo $this->getSkinUrl('images/home/adc_cart_banner.png');?>" alt="" class="cart_img"/>
			<div class="content_order">
				<h1>How to Order</h1>
				<p>
					1. Select the product from Brand, Generic or you can search the product by clicking on "Search" option.</p>
				<a href="<?php echo $this->getBaseUrl();?>content/88-order-online/" class="readmore" target="_blank"><span>Read More</span></a>
			</div>
		</div>
		

		<div class="echeck">
			<div class="echeck_inner">
				<img src="<?php echo $this->getSkinUrl('images/home/echeck.jpg');?>" alt="" class="echeck_img"/>
				<div class="content_order">
					<h1>Pay by eCheck & get a</h1>
					<h2>Discount of US $ 10.00*</h2>
					<div class="app_term">*Applicable on more that US $100.00 purchase.</div>
					<br/>				
					<a href="<?php echo $this->getBaseUrl();?>content/114-echeck/" class="readmore" target="_blank"><span>Learn More</span></a>
					
				</div>
			</div>
		</div>
			<div class="combopack">
					<img src="<?php echo $this->getSkinUrl('images/home/combooffer.png');?>" alt="" width="100%" class="combopack_img"/>
					<a class="comboclass" href="<?php echo $this->getBaseUrl().'contactcustom/index/combopack';?>">
						<img src="<?php echo $this->getSkinUrl('images/home/buynow.png');?>" alt="" />
					</a>
			</div>
	</div>
</div>
