<div id="banner">
  <div class="slides_container">
    <div id="demo">
      <div class="inner">
        <div id="primary-show" class="protoshow">
          <ul class="show">
            <li class="slide"> <a><img src="<?php echo $this->getSkinUrl() ?>images/banner2.jpg" /></a></li>
            <li class="slide"> <a><img src="<?php echo $this->getSkinUrl() ?>images/banner3.jpg" /></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
	<script src="http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js"></script>
	<script src="js/slides.min.jquery.js"></script--> 
<!--<script>
		jQuery(function(){
			jQuery('#slides').slides({
				preload: true,
				preloadImage: 'http://reliablerx.iksuladev.com/skin/frontend/reliablerx/default/images/loading.gif',
				play: 3000,
				pause: 1500,
				hoverPause: true
			});
		});
	</script>-->