<div class="main_menu">
	<div class="shop"><a href="#"><img src="http://reliablerx.iksuladev.com/skin/frontend/reliablerx/default/images/shop.jpg"></a><span><a href="<?php echo $this->getUrl('')?>">SHOP</a></span></div>
	<div class="products"><a href="<?php echo $this->getUrl('all.html')?>"><img src="http://reliablerx.iksuladev.com/skin/frontend/reliablerx/default/images/products.jpg"><span>PRODUCTS</a></span></div>
	<div class="wishlist"><a href="#"><img src="http://reliablerx.iksuladev.com/skin/frontend/reliablerx/default/images/wishlist.jpg"></a><span><a href="<?php echo $this->getUrl('wishlist')?>">WISHLIST</a></span></div>
</div>